### ISSUE TITLE
Feature: Reserve not met

### ISSUE THREAD

**Issue by Shybella** [Ewoutvans/Auction#8]
Simple reserve not met as a option when listing an item.

If seller has reserve of 100 on the item and bids do not exceed 100 cancel the auction.

**Comment by Ewoutvans** [comment]
I don't understand what you mean with the reserve, can you give more details and example?

**Comment by Shybella** [comment]
Hello, 

Reserve price is the amount that bidding must reach for the item to actually sell. If the player adds a reserve of 100 and bidding only reaches 90 the item does not sell and gets returned to the player.

Reserves are used a lot in real world auctions.

This isn't a super needed feature or even one at all. It's just something auctions do in the real world very frequently.

**Comment by Ewoutvans** [comment]
I think this is to complicated.
On my server players just start at the minimum they want

**Comment by Shybella** [comment]
I agree
